#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Waiting for postgres..."

while ! nc -z postgres 5432; do
  sleep 0.1
done

echo "PostgreSQL started"

python manage.py makemigrations
python manage.py migrate
python manage.py loaddata config/fixtures/*.json

exec "$@"
