version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: django-app
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:12.3
    container_name: django-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: django-mailhog
    ports:
      - "8025:8025"

# 2020.07.18-DEA
