version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
