version: "3"

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    command: /start.sh
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - caddy

  postgres:
    image: postgres:15.3-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  caddy:
    image: caddy:2-alpine
    restart: always
    volumes:
      - ./compose/production/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    ports:
      - 80:80
      - 443:443

volumes:
  postgres-data:
  caddy-data:
  caddy-config:
