services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    restart: always
    volumes:
      - django-static:/app/static
      - django-media:/app/media
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - backend

  caddy:
    image: caddy:2-alpine
    restart: always
    volumes:
      - ./compose/production/caddy/Caddyfile:/etc/caddy/Caddyfile
      - django-static:/app/static
      - django-media:/app/media
    env_file:
      - .env
    networks:
      backend:
      ingress-web:
        aliases:
          - ${APP_UNIQUE_IDENTIFIER}

volumes:
  django-media:
  django-static:
  postgres-data:

networks:
  backend:
  ingress-web:
    external: true
