#!/bin/bash

echo "Activating virtual enviroment (venv) ..."
source ~/venv/bin/activate
if [ "$VIRTUAL_ENV" == "" ]; then
  exit 1
fi
echo "Done"

echo "Syncing database ..."
python manage.py makemigrations
if [ ! $? -eq 0 ]; then
  exit 1
fi
python manage.py migrate
if [ ! $? -eq 0 ]; then
  exit 1
fi
echo "Done"

echo "Runnning server ..."
python manage.py runserver 0.0.0.0:8000
echo "Done"

# 2020.04.01-DEA
